/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab7.frontend;

import static com.mycompany.lab7.frontend.VectorDrawingApplication.hh;
import java.awt.Point;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Detective_CN
 */
public class RecData extends  javax.swing.JDialog implements Node {
    //JFrame pp;
    Rectangle rec =new Rectangle();
    /**
     * Creates new form RecData
     */
    public RecData(JFrame parent) {
         super(parent, "Rectangle probleties", ModalityType.DOCUMENT_MODAL);
        initComponents();
        this.setVisible(true);
    }
    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        first = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        hight = new javax.swing.JLabel();
        width = new javax.swing.JLabel();
        X1 = new javax.swing.JTextField();
        Y1 = new javax.swing.JTextField();
        Hight = new javax.swing.JTextField();
        Width = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Rectangle Data");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("  Enter point, hight and width");
        jLabel1.setOpaque(true);

        first.setBackground(new java.awt.Color(51, 255, 255));
        first.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        first.setForeground(new java.awt.Color(0, 0, 0));
        first.setText("   X1");
        first.setOpaque(true);

        y1.setBackground(new java.awt.Color(51, 255, 255));
        y1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        y1.setForeground(new java.awt.Color(0, 0, 0));
        y1.setText("    Y1");
        y1.setOpaque(true);

        hight.setBackground(new java.awt.Color(51, 255, 255));
        hight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hight.setForeground(new java.awt.Color(0, 0, 0));
        hight.setText("   Hight");
        hight.setOpaque(true);

        width.setBackground(new java.awt.Color(51, 255, 255));
        width.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        width.setForeground(new java.awt.Color(0, 0, 0));
        width.setText("   Width");
        width.setOpaque(true);

        X1.setBackground(new java.awt.Color(255, 255, 255));
        X1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        X1.setForeground(new java.awt.Color(0, 0, 0));

        Y1.setBackground(new java.awt.Color(255, 255, 255));
        Y1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Y1.setForeground(new java.awt.Color(0, 0, 0));

        Hight.setBackground(new java.awt.Color(255, 255, 255));
        Hight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Hight.setForeground(new java.awt.Color(0, 0, 0));

        Width.setBackground(new java.awt.Color(255, 255, 255));
        Width.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Width.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Draw");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(y1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(width, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Y1)
                            .addComponent(X1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hight, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Width, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(first, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(X1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Y1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(y1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hight, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hight, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Width, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         this.setVisible(false);
       ((JFrame)(this.getParentNode())).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                  String x1 =null,y1= null,hight=null,width=null;
        boolean flag =true;
        boolean negative =false;
        
        Point p =new Point();
        int recHigth=0,recWidth=0;
        x1 =this.X1.getText();
        y1 =this.Y1.getText();
        hight =this.Hight.getText();
        width =this.Width.getText();
        //System.out.println("readdddd");
        
        if(x1.equals("")||y1.equals("")||hight.equals("")||width.equals(""))
            flag = false;
        else{
                negative = false;
                //System.out.println("dataatstcats");
                p.x=Integer.parseInt(x1);
                p.y=Integer.parseInt(y1);
                recHigth=Integer.parseInt(hight);
                recWidth=Integer.parseInt(width);
                if(p.x < 0 || p.y<0 ||recHigth <0 || recWidth <0){
                    negative =true;
                JOptionPane.showMessageDialog(null,"You must enter a positive number");
            }
        }
        
        if(flag ==true &&!negative)
        {
            
            //System.out.println("ggggg");
        
        rec.setPosition(p);
        rec.getHightAndWidth(recHigth, recWidth);
        
        JOptionPane.showMessageDialog(null,"Data is successfully added");
        
        this.X1.setText("");
        this.Y1.setText("");
        this.Hight.setText("");
        this.Width.setText("");
         this.setVisible(false);
       ((JFrame)(this.getParentNode())).setVisible(true);
        }
        else if(flag == false && !negative)
            JOptionPane.showMessageDialog(null,"Some fields are empty");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new RecData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hight;
    private javax.swing.JTextField Width;
    private javax.swing.JTextField X1;
    private javax.swing.JTextField Y1;
    private javax.swing.JLabel first;
    private javax.swing.JLabel hight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel width;
    private javax.swing.JLabel y1;
    // End of variables declaration//GEN-END:variables
private Node parent=hh;
   @Override
    public void setParentNode(Node node) {
        this.parent=node;
    }

    @Override
    public Node getParentNode() {
        return parent;
    }

    public Rectangle getRectangle() {
        return rec;
    }
    
}
