/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab7.frontend;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JColorChooser;


/**
 *
 * @author User
 */
public class VectorDrawingApplication extends javax.swing.JFrame implements Node {
    static VectorDrawingApplication hh =new VectorDrawingApplication();
    private myPanel2 engine;
    private Graphics g;
    //private myPanel2 engine =new myPanel2();
    /**
     * Creates new form VectorDrawingApplication
     */
 private void resetComboBox(){
      jComboBox1.removeAllItems();
        Rectangle.setI();
        LineSegment.setI();
        Circle.setI();  
}
    public VectorDrawingApplication() {
        
        initComponents();
        engine = myPanel21;
        this.g = myPanel21.getGraphics();
        myPanel21.paintComponent(g);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        circle = new javax.swing.JButton();
        lineSegment = new javax.swing.JButton();
        square = new javax.swing.JButton();
        rectangle = new javax.swing.JButton();
        colorize = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        myPanel21 = new com.mycompany.lab7.frontend.myPanel2();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vector Drawing Application");
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Select shape");
        jLabel1.setOpaque(true);

        circle.setBackground(new java.awt.Color(204, 204, 255));
        circle.setForeground(new java.awt.Color(0, 0, 0));
        circle.setText("Circle");
        circle.setOpaque(true);
        circle.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                circleInputMethodTextChanged(evt);
            }
        });
        circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleActionPerformed(evt);
            }
        });

        lineSegment.setBackground(new java.awt.Color(204, 204, 255));
        lineSegment.setForeground(new java.awt.Color(0, 0, 0));
        lineSegment.setText("Line segment");
        lineSegment.setOpaque(true);
        lineSegment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineSegmentActionPerformed(evt);
            }
        });

        square.setBackground(new java.awt.Color(204, 204, 255));
        square.setForeground(new java.awt.Color(0, 0, 0));
        square.setText("Square");
        square.setOpaque(true);
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });

        rectangle.setBackground(new java.awt.Color(204, 204, 255));
        rectangle.setForeground(new java.awt.Color(0, 0, 0));
        rectangle.setText("Rectangle");
        rectangle.setOpaque(true);
        rectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangleActionPerformed(evt);
            }
        });

        colorize.setBackground(new java.awt.Color(204, 204, 255));
        colorize.setForeground(new java.awt.Color(0, 0, 0));
        colorize.setText("Colorize");
        colorize.setOpaque(true);
        colorize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorizeActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(204, 204, 255));
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("Delete");
        delete.setOpaque(true);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        myPanel21.setBackground(new java.awt.Color(255, 255, 255));
        myPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        myPanel21.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout myPanel21Layout = new javax.swing.GroupLayout(myPanel21);
        myPanel21.setLayout(myPanel21Layout);
        myPanel21Layout.setHorizontalGroup(
            myPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        myPanel21Layout.setVerticalGroup(
            myPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colorize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(circle)
                        .addGap(18, 18, 18)
                        .addComponent(lineSegment)
                        .addGap(18, 18, 18)
                        .addComponent(square)
                        .addGap(18, 18, 18)
                        .addComponent(rectangle))
                    .addComponent(myPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circle)
                    .addComponent(lineSegment)
                    .addComponent(square)
                    .addComponent(rectangle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colorize)
                            .addComponent(delete)))
                    .addComponent(myPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lineSegmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineSegmentActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        lineData li =new lineData(hh);
        this.setVisible(true);
        li.setParentNode((Node)hh);
        
        LineSegment line = li.getLineSegment(); 
        
        Color borderColor = JColorChooser.showDialog(null,"Choose border color", Color.black);
        line.setColor(borderColor);
        line.draw(g);
        engine.addShape(line);
        engine.refresh(null);
        
            hh.UpdateBox();    
    }//GEN-LAST:event_lineSegmentActionPerformed

    private void circleInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_circleInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_circleInputMethodTextChanged

    private void circleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleActionPerformed
        // TODO add your handling code here:
    
        
          this.setVisible(false);
        CircleGUI li =new CircleGUI(hh);
        
        Circle cc= li.getCc(); 
        Color borderColor = JColorChooser.showDialog(null,"Choose border color", Color.black);
        Color FillColor = JColorChooser.showDialog(null,"Choose Fill color", Color.black);
        cc.setColor(borderColor);
        cc.setFillColor(FillColor);
       
        cc.draw(g);
        engine.addShape(cc);
        engine.refresh(null);
         hh.UpdateBox();
        

    }//GEN-LAST:event_circleActionPerformed

    private void rectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangleActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RecData li =new RecData(hh);
      
        Rectangle rec = li.getRectangle(); 
        Color borderColor = JColorChooser.showDialog(null,"Choose border color", Color.black);
        Color FillColor = JColorChooser.showDialog(null,"Choose Fill color", Color.black);
        rec.setColor(borderColor);
        rec.setFillColor(FillColor);
       
        rec.draw(g);
        engine.addShape(rec);
        engine.refresh(null);
         hh.UpdateBox();
    }//GEN-LAST:event_rectangleActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Square squaredata =new Square(hh);
       
        
        Rectangle sq = squaredata.getRectangle(); 
        Color borderColor = JColorChooser.showDialog(null,"Choose border color", Color.black);
        Color FillColor = JColorChooser.showDialog(null,"Choose Fill color", Color.black);
        sq.setColor(borderColor);
        sq.setFillColor(FillColor);
      
        sq.draw(g);
        engine.paintComponent(g);
        engine.addShape(sq);
        engine.refresh(null);
            
        hh.UpdateBox();
        
    }//GEN-LAST:event_squareActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void colorizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorizeActionPerformed
        // TODO add your handling code here:
        Shape [] a =engine.getShapes();
        int x =jComboBox1.getSelectedIndex();
        Shape shapeToColor= a[x];
        engine.removeShape(shapeToColor);
        
        Color borderColor = JColorChooser.showDialog(null,"Choose border color", Color.black);
        Color FillColor = JColorChooser.showDialog(null,"Choose Fill color", Color.black);
        shapeToColor.setColor(borderColor);
        shapeToColor.setFillColor(FillColor);
        
        
        shapeToColor.draw(g);
        engine.paintComponent(g);
        engine.addShape(shapeToColor);
        engine.refresh(null); 
        hh.UpdateBox();
    }//GEN-LAST:event_colorizeActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
        Shape [] a =engine.getShapes();
        int i =jComboBox1.getSelectedIndex();
        
        Shape shapeToDelete= a[i];
            engine.removeShape(shapeToDelete);
            engine.refresh(null); 
        
        hh.UpdateBox();
        
        
        
        
    }//GEN-LAST:event_deleteActionPerformed

    public void UpdateBox(){
        hh.resetComboBox();
        Shape [] a =engine.getShapes();
        int size = a.length;
        for(int i=0;i<size;i++)
        {
                jComboBox1.addItem(a[i].toString());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VectorDrawingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VectorDrawingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VectorDrawingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VectorDrawingApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                hh=new VectorDrawingApplication();
               hh.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circle;
    private javax.swing.JButton colorize;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lineSegment;
    private com.mycompany.lab7.frontend.myPanel2 myPanel21;
    private javax.swing.JButton rectangle;
    private javax.swing.JButton square;
    // End of variables declaration//GEN-END:variables

    private Node parent;

    @Override
    public void setParentNode(Node node) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public Node getParentNode() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
